add topic variabel & tipe data, input & output
wrideveloper/roadmap-oop pull request #5
Opened 2020-07-16 14:03 UTC by ardananjungkusuma

2020-07-17 13:57 UTC, SultanKs4 requested changes
this is my perspective

2020-07-17 13:57 UTC, SultanKs4 commented on materi/basic/inputoutput.md
> +Pada program diatas kita sudah bisa menerima inputan dan mengeluarkannya dalam output. Hal yang harus diperhatikan adalah sebagai berikut `Scanner sc = new Scanner(System.in);` sc disini merupakan va
1. jangan jadi 1 line untuk memberikan penjelasan lebih baik poin - poinnya dalam list
2. berikan link referensi untuk Tipe data scanner yang lebih lengkap jika tidak menyebutkan semuanya

```suggestion
Pada program diatas kita sudah bisa menerima inputan dan mengeluarkannya dalam output. Hal yang harus diperhatikan adalah sebagai berikut:

1. Peletakan `import java.util.Scanner;` sesudah package.
2. `Scanner sc = new Scanner(System.in);` sc disini merupakan variable, nama dari variable ini bebas sehingga dapat kita ganti apa saja. Contohnya: `Scanner input = new Scanner(System.in);`.
3. `sc.next...();`, contoh: `sc.nextLine();`, `nextLine();` digunakan untuk membaca inputan berupa kalimat / `Strings` untuk membaca tipe data yang lain dapet menggunakan method lain, beberapa contoh method yang ada: 
  
- `nextInt()` untuk membaca inputan bertipe data Integer (int).

- `nextDouble()` untuk membaca inputan bertipe data Double.

- selengkapnya [Scanner Input Types](https://www.w3schools.com/java/java_user_input.asp)

4. Perbedaan `System.out.println` dan `System.out.print` adalah jika kita menggunakan `println` maka kita akan membuat baris baru namun jika `print` biasa maka tidak akan membuat baris baru.

```

2020-07-18 13:18 UTC, ardananjungkusuma commented
Updated!

2020-07-18 14:57 UTC, SultanKs4 approved these changes
LGTM!

2020-07-18 14:57 UTC, merged